aid-ter ARIA
solid/solidproject.org pull request #348
Opened 2020-09-09 04:13 UTC by FutureLearnSole

1. As a
2. want to be able to 
3.  way as other 

_Solid is a technology, like the Web, but a new level of standard which adds to the existing protocols to make it more powerful, particularly to empower individuals at home and at work._

2020-09-09 08:29 UTC, Vinnl requested changes
Thanks for caring about this! Unfortunately, when adding accessibility data, we have to be very careful about doing it correctly, or we may end up making things even worse for people relying on it. And unfortunately, most of these changes are in that category. So please take a look at my comments, so that we can merge in the remaining ones :)

2020-09-09 08:29 UTC, Vinnl commented on _includes/footer.html
> +<footer id="footer" class="footer" role="navigation">
[By default](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer), a `<footer>` has  the role [`contentinfo`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Contentinfo_role):

> The contentinfo landmark role is used to identify information repeated at the end of every page of a website, including copyright information, **navigation links**, and privacy statements. This section is commonly called a footer.

(Emphasis mine.)

Thus, I don't think we need this role here:

```suggestion
<footer id="footer" class="footer">
```

2020-09-09 08:29 UTC, Vinnl commented on _includes/footer.html
> +	    aria-label="Github"
This is already covered by [the `alt` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#Attributes).

```suggestion
```

2020-09-09 08:29 UTC, Vinnl commented on _includes/footer.html
> +	    aria-label="Twitter"
This is already covered by [the `alt` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#Attributes).

```suggestion
```

2020-09-09 08:29 UTC, Vinnl commented on _includes/footer.html
> +	    aria-label="Vimeo"
This is already covered by [the `alt` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#Attributes).

```suggestion
```

2020-09-09 08:29 UTC, Vinnl commented on _includes/header.html
> +	    aria-label="{{ item.name }}"
The content of this element already serves as the label, so we don't need to add a different label for screen reader users :)

```suggestion
```

2020-09-09 08:29 UTC, Vinnl commented on _includes/subscribe.html
> +<div id="newsletter" class="section" aria-label="newsletter">
The title (`<h2>`) and contents of this `<div>` already describe it. In fact, I think (but haven't tested that) that adding a label here might even prevent the contents from being spoken by screen readers.

```suggestion
<div id="newsletter" class="section">
```

2020-09-09 08:29 UTC, Vinnl commented on _includes/talk.html
> +<div class="talk" aria-label="a Solid talk by {{ include.speaker }}">
As above, this `<div>` is already sufficiently described by its contents.

2020-09-09 08:29 UTC, Vinnl commented on _includes/breadcrumbs.html
> +  <nav id="breadcrumb" class="breadcrumb" aria-label="breadcrumbs">
I'm not sure how common the terminology "breadcrumbs" is among non-developers, but in any case, the fact that this is a navigation element should already provide enough contents for users of screen readers.

```suggestion
  <nav id="breadcrumb" class="breadcrumb">
```

2020-09-10 04:50 UTC, FutureLearnSole reviewed
_rewrite co-auth_
good ARIA bad ARIA no ARIA

2020-09-10 06:04 UTC, FutureLearnSole commented on _includes/talk.html
> +<div class="talk" aria-label="a Solid talk by {{ include.speaker }}">
```suggestion
<div class="talk">
```

2020-09-10 06:10 UTC, FutureLearnSole commented on _includes/footer.html
> +      <a class="navbar-item" href="{{site.baseUrl}}/"> <img
```suggestion
      <a class="navbar-item" href="{{site.baseUrl}}/">
        <img
```

2020-09-10 06:18 UTC, FutureLearnSole commented on _includes/subscribe.html
> +</div>
```suggestion
</div>\ No newline at end of file
```

2020-09-10 06:18 UTC, FutureLearnSole commented on _includes/talk.html
> +</div>
```suggestion
</div>\ No newline at end of file
```

2020-09-10 06:19 UTC, FutureLearnSole commented on _includes/toc-apps.html
> +</ul>
```suggestion
</ul>\ No newline at end of file
```

2020-09-10 06:19 UTC, FutureLearnSole commented on _includes/toc-pod-server.html
> +</ul>
```suggestion
</ul>\ No newline at end of file
```

2020-09-10 06:22 UTC, FutureLearnSole commented on _includes/subscribe.html
> +</div>\ No newline at end of file
```suggestion
</div><EOL>
```

2020-09-10 06:23 UTC, FutureLearnSole commented on _includes/subscribe.html
> +</div><EOL>
```suggestion
</div><CR><LF>
```

2020-09-10 06:25 UTC, FutureLearnSole commented on _includes/talk.html
> +</div>\ No newline at end of file
```suggestion
</div>
```

2020-09-10 06:34 UTC, FutureLearnSole commented on _includes/toc-apps.html
> +</ul>\ No newline at end of file
```suggestion
</ul>;\n
```

2020-09-10 06:35 UTC, FutureLearnSole commented on _includes/toc-pod-server.html
> +</ul>\ No newline at end of file
```suggestion
</ul>;\n
```

2020-09-10 06:35 UTC, FutureLearnSole commented on _includes/subscribe.html
> +</div><CR><LF>
```suggestion
</div>;\n
```

2020-09-10 07:29 UTC, Vinnl commented
Thanks @FutureLearnSole, I've fixed the newline issues and resubmitted your PR in #349, which should be reviewed and merged soon :) Thanks!

2020-09-10 07:29 UTC, closed without merging