Added Penny to the list of Solid Apps
solid/solidproject.org pull request #600
Opened 2021-07-22 09:38 UTC by nicolasmondada

Added Penny from Vincent Turu to the list of Solid Apps

2021-07-26 18:15 UTC, kay-kim requested changes

2021-07-26 18:15 UTC, kay-kim commented on pages/use-solid/apps.md
> +| [Penny](https://penny.vincenttunru.com/)                                   | File browser. <br>- [Source code](https://github.com/linkeddata/warp) [MIT License Copyright (c) 2014](https://github.co
Hey Nick -- 
this row and the below row seems to have gotten somehow entangled.

This Penny row seems to link to the Warp application  whereas below, in the Historical Solid Apps section, you seem to have clobbered Mark Book source and license link with Vincent's

2022-01-21 15:49 UTC, KyraAssaad commented
@Vinnl Penny is listed on https://solidproject.org/developers/tools/, do you want it listed on both pages? 

@MarrelleBailey @justinwb I'm making a note of this for the redesign - what's the difference between `Tools and Libraries` vs `Apps`?

2022-01-21 15:53 UTC, Vinnl commented
@KyraAssaad No, I'm fine with it not being on the apps page; I'm explicitly "advertising" it as a developer tool rather than a user-facing app. I don't think many non-developer users would be happy using Penny or otherwise browsing raw data on their Pod.

2022-01-21 16:11 UTC, KyraAssaad commented
Closing this since Penny is listed on https://solidproject.org/developers/tools/ already!

2022-01-21 16:11 UTC, closed without merging

2022-01-21 17:19 UTC, jeff-zucker commented
I'm the one who came up with the original breakout - tools, libraries, and apps.  At one point I suggested lumping tools back in with apps and would still be fine with that.  My mental breakdown is this : a library is something that is can not be used directly but is called by an app.  A tool is something developers use to manage their apps and data.  Molid fits that and is of little use to anyone but developers.  Penny and Solid-IDE and SolidShell I think can be used by users and so probably belong with Apps, especialy if there is a "Pod Management" section within apps.  Data-Kitchen includes the kitchen sink so is both a tool and a super-app.   I don't have a strong opinion but I guess I'd move tools to apps.

2022-01-21 17:24 UTC, KyraAssaad commented
Thanks for this info, @jeff-zucker! That makes sense. I think the confusing part for me is that "Tools and Libraries" are together but "Apps" is a separate page. We'll probably keep the designation you explained, but maybe reorganize the pages so it's more clear