Split out CSS-specific instructions from self-hosting overview
solid/solidproject.org pull request #690
Opened 2022-04-19 08:57 UTC by michielbdejong

2022-04-19 08:59 UTC, michielbdejong commented
This fixes #689.

2022-04-22 07:42 UTC, RubenVerborgh submitted a review, later dismissed
Need to hold until https://github.com/solid/test-suite/issues/132 has been decided.

2022-04-25 10:02 UTC, RubenVerborgh commented
Closing until we have answers to the following questions:
- Do a majority of test-suite panel and editors agree that the table is a correct and representative measure of spec compatibility?
- Do a majority of test-suite panel and editors agree that the table can be compiled and published without implementer consent?

Please link to a majority vote result in order to reopen.

2022-05-04 09:33 UTC, timbl commented
The move of infomration into more logical set of pages does *not* have to wait for test stuff to be decided, surely?

2022-05-04 10:09 UTC, csarven requested changes

2022-05-04 10:09 UTC, csarven commented on _posts/developers/pod-server/2019-01-01-00_overview.md
> +See [the features matrix](https://github.com/solid/test-suite#table) to find out which server implementation supports which required and/or optional parts of the Solid spec.
This is new information that I think is outside the scope of the issue that this PR intends to fix/resolve. I suggest to omit this for the time being.

```suggestion
```

2022-05-04 10:11 UTC, csarven commented
With the exception of updating as per https://github.com/solid/solidproject.org/pull/690#discussion_r864667235 , this PR is fine as far reorganising existing information goes. solidproject.org happens to include the instructions to help potential users but if that information is subject to going stale or better to link out to an authoritative document that's published by the CSS team somewhere and updated more frequently, then that can work too.

2022-05-04 16:49 UTC, RubenVerborgh commented
> The move of infomration into more logical set of pages does _not_ have to wait for test stuff to be decided, surely?

No, but https://github.com/solid/solidproject.org/pull/690/commits/2b28f36d8bc06f53ca5f4b940bd527eebea3761e was sneaked in, as @csarven also noted. Without that commit, this PR is fine.

2022-05-10 07:53 UTC, csarven approved these changes

2023-11-21 14:50 UTC, csarven reviewed
I think this PR is no longer applicable as the site seems to have moved on with other changes (from other PRs): https://solidproject.org/users/get-a-pod#self-host-your-pod

@michielbdejong , can we close this?

Sorry that this PR was closed, reopened, and then gone stale. Solid Team should better process open PRs...

2023-12-21 08:07 UTC, closed without merging