add Community helps to getting started page
solid/solidproject.org pull request #799
Opened 2023-07-27 07:51 UTC by soltanireza65

2023-07-27 18:08 UTC, TallTed requested changes

2023-07-27 18:08 UTC, TallTed commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +## Community helps
```suggestion
## Community assistance
```

2023-07-27 18:08 UTC, TallTed commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +Check some of the applications. Some interesting approaches
```suggestion
Check some of the applications. Some interesting approaches follow:
```

2023-07-27 18:08 UTC, TallTed commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +- solid-uix https://github.com/SolidOS/solid-uix (Native Web Components)
```suggestion
- **PodOS** (Web Components) https://github.com/pod-os/PodOS
- **solid-uix** (Native Web Components) https://github.com/SolidOS/solid-uix
```

2023-07-30 12:57 UTC, soltanireza65 commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +## Community helps
fixed

2023-07-30 12:57 UTC, soltanireza65 commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +Check some of the applications. Some interesting approaches
appliyed

2023-07-30 12:57 UTC, soltanireza65 commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +- solid-uix https://github.com/SolidOS/solid-uix (Native Web Components)
appliyed

2023-07-30 12:57 UTC, soltanireza65 commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +- [Solid Apps](https://solidproject.org/apps)
appliyed

2023-08-11 10:32 UTC, soltanireza65 commented
@TallTed 
I've just added a new section "Youtube videos"

2023-08-11 18:02 UTC, TallTed requested changes
Small stuff

2023-08-11 18:02 UTC, TallTed commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +you're ready to develop your own app. Various Solid client libraries may provide a beginning app tutorial; for example, the [Inrupt JS Client Library tutorial](https://docs.inrupt.com/developer-tools
```suggestion
you're ready to develop your own app. Various Solid client libraries may provide a  tutorial for beginners; for example, Inrupt offers the [JS Client Library tutorial](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/getting-started/).
```

2023-08-11 18:02 UTC, TallTed commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +Check some of the applications. Some interesting approaches follow:
```suggestion
Check out some of the existing applications. Some interesting approaches follow:
```

2023-08-11 18:02 UTC, TallTed commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +- [How we're doing Solid - In less than 5 minutes](https://www.youtube.com/watch?v=CqI15zs1NHw)
```suggestion
- [How we're doing Solid — in fewer than 5 minutes](https://www.youtube.com/watch?v=CqI15zs1NHw)
```

2023-08-17 07:44 UTC, soltanireza65 commented
> Small stuff

fixed

2023-08-24 06:58 UTC, michielbdejong commented
@TallTed can you re-review please?

2023-08-24 13:32 UTC, TallTed requested changes
Different small stuff :-)

2023-09-07 07:14 UTC, soltanireza65 commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +you're ready to develop your own app. Various Solid client libraries may provide a  tutorial for beginners; for example, Inrupt offers the [JS Client Library tutorial](https://docs.inrupt.com/develop
applied

2023-09-07 07:14 UTC, soltanireza65 commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +Solid With web frameworks:
applied

2023-09-07 07:14 UTC, soltanireza65 commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +- **ember-solid**: [Video Tutorial](https://nextcloud.hellofuture.be/s/nYYNwGceFSNotJY)  which should be start-to-finish Solid Ember App (Aad Versteden)
applied

2023-09-07 07:14 UTC, soltanireza65 commented on _posts/developers/apps/inrupt-tutorial/2021-08-03-00_getting-started.md
> +- **[solid-react-app-tutorial](https://virginiabalseiro.com/blog/solid-react-app-tutorial)**
applied

2023-09-07 07:18 UTC, soltanireza65 commented
@TallTed 
I've just applied the requested changes,
As part of the last 2 commits, I've just added my new 2 solid apps to the apps page.
that's why I've just updated the PR title.

2023-09-07 08:03 UTC, michielbdejong approved these changes

2023-09-07 15:42 UTC, TallTed commented
@soltanireza65 — It is often better to use the "Commit suggestion" or "Add suggestion to batch" buttons, as these both apply the suggested change *and* resolve the conversation without requiring manual review of manually applied changes (which I'm doing now)....

2023-09-07 15:46 UTC, TallTed approved these changes

2023-09-18 08:43 UTC, merged