Replace people by individuals and communities
solid/solidproject.org pull request #814
Opened 2023-11-10 21:27 UTC by lecoqlibre

This is a proposal for issue #813.

2023-11-13 15:03 UTC, TallTed commented on pages/home.md
> +              control which people, organizations and applications can access it.
```suggestion
              control which people, organizations, and applications can access it.
```

2023-11-13 15:05 UTC, TallTed requested changes
Just a couple of commas

2023-11-13 15:05 UTC, TallTed commented on pages/home.md
> +              control which people, organizations and applications can access it.
```suggestion
              control which people, organizations, and applications can access it.
```

2023-11-13 15:05 UTC, TallTed commented on pages/home.md
> +              determine whether a person, organization or application has access to a
```suggestion
              determine whether a person, organization, or application has access to a 
```

2023-12-15 15:07 UTC, lecoqlibre commented on pages/home.md
> +              determine whether a person, organization, or application has access to a
OK was not sure of this one, I included it.

2023-12-15 17:55 UTC, TallTed approved these changes

2023-12-15 18:04 UTC, csarven approved these changes

2023-12-17 13:05 UTC, lecoqlibre commented
Thank you for your reviews, can someone merge this PR? Maybe @Vinnl?

2023-12-20 09:40 UTC, VirginiaBalseiro approved these changes

2023-12-21 10:43 UTC, VirginiaBalseiro commented
@lecoqlibre if you can rebase this, I'll merge.

2023-12-24 11:08 UTC, merged