add LDO to dev tools
solid/solidproject.org pull request #873
Opened 2024-04-24 18:34 UTC by elf-pavlik

ping @jaxoncreed

2024-04-24 18:38 UTC, csarven approved these changes

2024-04-24 18:39 UTC, jeff-zucker approved these changes

2024-04-24 19:00 UTC, TallTed requested changes
Punctuations fixes

2024-04-24 19:00 UTC, TallTed commented on _posts/developers/apps/tools/2019-01-01-00_overview.md
>       * [Soukai-solid](https://github.com/NoelDeMartin/soukai-solid) -  A [Soukai ODM](https://soukai.js.org/) extension adapting Solid to the engine
```suggestion
     * [LDflex for Solid](https://github.com/solid/query-ldflex) — A library for making RDF querying easy
     * [LDO](https://ldo.js.org) — Solid and RDF without the Complexity
     * [GraphQL-LD for Solid](https://github.com/rubensworks/graphql-ld-comunica-solid.js) — A way to query Linked Data using GraphQL
     * [rdflib](https://github.com/linkeddata/rdflib.js/) — A library for advanced manipulation of RDF
     * [Soukai-solid](https://github.com/NoelDeMartin/soukai-solid) — A [Soukai ODM](https://soukai.js.org/) extension adapting Solid to the engine
```

2024-05-03 07:42 UTC, jaxoncreed approved these changes
LGTM

2024-06-11 08:20 UTC, michielbdejong approved these changes

2024-06-11 08:20 UTC, merged